### ISSUE TITLE
Secondary owner

### ISSUE THREAD

**Issue by LuckyPass** [Cyclone-Bot-List/cbl-issues#1]
Secondary owner doesn't save

**Comment by Zaid-maker** [comment]
This is because second owner must be in the server, so the bot read that user too

**Comment by Zaid-maker** [comment]
try to invite that user in the server and try again

**Comment by LuckyPass** [comment]
> try to invite that user in the server and try again

Still doesn't work

**Comment by Zaid-maker** [comment]
will be fixed!
